"""The ORM models must declare every constraint the migrations create.

For most of this project's life the models declared 36 foreign-key columns as plain
``BigInteger`` while the migrations created real ``FOREIGN KEY`` constraints for them.
The database was correct; the models lied about it. The consequence was a loaded gun:
``alembic revision --autogenerate`` compares the models against the database, so the very
next autogenerated migration would have emitted ``op.drop_constraint`` for **all 36** —
silently destroying referential integrity across Leave, Payroll, Settlements, Approvals
and RBAC.

This test asserts the models and the migrations agree on the *shape* of the schema. It
does not need a database: it compares the FK constraints declared in ``Base.metadata``
against the ones the migration files create.
"""

from __future__ import annotations

import re
from pathlib import Path

import app.main  # noqa: F401  - imports every module, so Base.metadata is fully populated
from app.core.database.base import Base

_MIGRATIONS = Path(__file__).resolve().parents[2] / "alembic" / "versions"


def _fks_declared_in_models() -> set[str]:
    names = set()
    for table in Base.metadata.tables.values():
        for fk in table.foreign_key_constraints:
            if fk.name:
                names.add(str(fk.name))
    return names


def _fks_created_by_migrations() -> set[str]:
    """Every ``fk_*`` constraint name a migration mentions, minus the ones it drops.

    The migrations name FKs three ways: a literal ``op.create_foreign_key("fk_...")``, an
    inline ``sa.ForeignKeyConstraint(..., name="fk_...")``, and — in the deferred-FK
    migrations (0008/0013/0016) — a *data table* of ``(table, column, name)`` tuples that
    a loop then feeds to ``create_foreign_key``. Matching only the call sites misses that
    third form entirely, which is how an earlier version of this test passed while 36 FKs
    were undeclared. So: scan for every ``fk_*`` literal, then subtract the dropped ones.
    """
    mentioned: set[str] = set()
    dropped: set[str] = set()
    for path in sorted(_MIGRATIONS.glob("*.py")):
        src = path.read_text()
        mentioned |= set(re.findall(r'"(fk_[a-z0-9_]+)"', src))
        dropped |= set(re.findall(r'drop_constraint\(\s*"(fk_[a-z0-9_]+)"', src))
    return mentioned - dropped


def test_models_declare_every_foreign_key_the_migrations_create() -> None:
    """A FK in the database but not on the model is one autogenerate will try to DROP."""
    in_migrations = _fks_created_by_migrations()
    in_models = _fks_declared_in_models()

    undeclared = sorted(in_migrations - in_models)
    assert not undeclared, (
        f"{len(undeclared)} foreign key(s) exist in the database but are not declared on "
        f"the ORM models. `alembic revision --autogenerate` will emit drop_constraint for "
        f"each of them: {undeclared}"
    )


def test_every_foreign_key_name_fits_postgres_identifier_limit() -> None:
    """PostgreSQL truncates identifiers at 63 chars; a longer name aborts the migration.

    Migration 0003 originally shipped a 79-character constraint name and could never have
    been applied to a real PostgreSQL — the whole chain was unrunnable and nobody noticed,
    because it had only ever been tested against mocks.
    """
    too_long = {
        name: len(name)
        for name in _fks_declared_in_models() | _fks_created_by_migrations()
        if len(name) > 63
    }
    assert not too_long, f"Constraint names exceed PostgreSQL's 63-char limit: {too_long}"
