import { ApprovalRequest } from "./types";

export const INITIAL_APPROVAL_REQUESTS: ApprovalRequest[] = [
  // --- PENDING REQUESTS ---
  {
    id: "req-p1",
    type: "Leave",
    subtype: "LWP",
    employeeCode: "22",
    employeeName: "Nitisha",
    designation: "Backend Developer",
    department: "Developer",
    details: {
      fromDate: "Tue 21 Jul",
      toDate: "Tue 21 Jul",
      totalDays: "1 Day",
      reason: "Personal work at home",
    },
    submittedDate: "20-07-2026 04:30 PM",
    status: "pending",
    pendingApprover: "Balkrushn koladiya (HR Manager)",
  },
  {
    id: "req-p2",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "15",
    employeeName: "Rahul Sharma",
    designation: "Frontend Developer",
    department: "Developer",
    details: {
      date: "20-07-2026",
      inTime: "09:30 AM",
      outTime: "06:30 PM",
      totalHours: "9 hrs 00 mins",
      reason: "Forgot biometric card at home",
    },
    submittedDate: "20-07-2026 06:35 PM",
    status: "pending",
    pendingApprover: "Balkrushn koladiya (HR Manager)",
  },
  {
    id: "req-p3",
    type: "Leave",
    subtype: "Casual Leave",
    employeeCode: "18",
    employeeName: "Anjali Gupta",
    designation: "HR Executive",
    department: "HR",
    details: {
      fromDate: "Wed 22 Jul",
      toDate: "Thu 23 Jul",
      totalDays: "2 Days",
      reason: "Out of town for family event",
    },
    submittedDate: "19-07-2026 11:15 AM",
    status: "pending",
    pendingApprover: "Balkrushn koladiya (HR Manager)",
  },
  {
    id: "req-p4",
    type: "Overtime",
    subtype: "Project Deadline OT",
    employeeCode: "29",
    employeeName: "Siddharth Verma",
    designation: "DevOps Engineer",
    department: "Infrastructure",
    details: {
      date: "19-07-2026",
      totalHours: "3 hrs 30 mins",
      reason: "Server migration and deployment release",
    },
    submittedDate: "20-07-2026 09:00 AM",
    status: "pending",
    pendingApprover: "Balkrushn koladiya (HR Manager)",
  },

  // --- APPROVED REQUESTS ---
  {
    id: "req-a1",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "57",
    employeeName: "Tulsi baladhiya",
    designation: "Graphic Designer",
    department: "Marketing",
    details: {
      date: "18-07-2026",
      inTime: "09:15 AM",
      outTime: "06:15 PM",
      reason: "Punch machine system offline during entry",
    },
    submittedDate: "18-07-2026 06:20 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "19-07-2026 10:00 AM",
    remarks: "Verified with CCTV footage.",
  },
  {
    id: "req-a2",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "33",
    employeeName: "Hepil Talaviya",
    designation: "Graphic Designer",
    department: "Graphic Designer",
    details: {
      date: "18-07-2026",
      inTime: "09:30 AM",
      outTime: "06:30 PM",
      reason: "Field visit for client shoot",
    },
    submittedDate: "18-07-2026 06:45 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "19-07-2026 10:05 AM",
    remarks: "Approved as per client visit pre-approval.",
  },
  {
    id: "req-a3",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "58",
    employeeName: "Savan Kamuni",
    designation: "marketing",
    department: "Marketing",
    details: {
      date: "18-07-2026",
      inTime: "09:00 AM",
      outTime: "06:00 PM",
      reason: "Device missed entry punch",
    },
    submittedDate: "18-07-2026 06:05 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "19-07-2026 10:10 AM",
    remarks: "Approved.",
  },
  {
    id: "req-a4",
    type: "Leave",
    subtype: "LWP",
    employeeCode: "54",
    employeeName: "Divyesh Pipaliya",
    designation: "marketing",
    department: "Marketing",
    details: {
      fromDate: "Thu 16 Jul",
      toDate: "Thu 16 Jul",
      totalDays: "1 Day",
      reason: "Urgent medical checkup",
    },
    submittedDate: "15-07-2026 04:00 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "16-07-2026 09:15 AM",
    remarks: "LWP granted.",
  },
  {
    id: "req-a5",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "58",
    employeeName: "Savan Kamuni",
    designation: "marketing",
    department: "Marketing",
    details: {
      date: "16-07-2026",
      inTime: "09:30 AM",
      outTime: "06:30 PM",
      reason: "Late punch adjustment",
    },
    submittedDate: "16-07-2026 06:40 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "17-07-2026 11:00 AM",
    remarks: "Approved by manager.",
  },
  {
    id: "req-a6",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "36",
    employeeName: "maulik bhadani",
    designation: "React.js",
    department: "Developer",
    details: {
      date: "16-07-2026",
      inTime: "09:00 AM",
      outTime: "06:00 PM",
      reason: "Biometric reader issue",
    },
    submittedDate: "16-07-2026 06:00 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "17-07-2026 11:05 AM",
    remarks: "System glitch confirmed.",
  },
  {
    id: "req-a7",
    type: "Leave",
    subtype: "Sick Leave",
    employeeCode: "42",
    employeeName: "Kunal Parikh",
    designation: "Quality Assurance",
    department: "QA",
    details: {
      fromDate: "Mon 13 Jul",
      toDate: "Tue 14 Jul",
      totalDays: "2 Days",
      reason: "Fever and doctor rest advice",
    },
    submittedDate: "13-07-2026 08:30 AM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "13-07-2026 09:00 AM",
    remarks: "Medical certificate provided.",
  },
  {
    id: "req-a8",
    type: "Comp Off",
    subtype: "Weekend Work Comp Off",
    employeeCode: "39",
    employeeName: "Hardik Vora",
    designation: "Database Admin",
    department: "Database",
    details: {
      fromDate: "Fri 10 Jul",
      toDate: "Fri 10 Jul",
      totalDays: "1 Day",
      reason: "Worked on Sunday server maintenance",
    },
    submittedDate: "08-07-2026 02:15 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "09-07-2026 10:30 AM",
    remarks: "Comp off credited for Sunday maintenance work.",
  },
  {
    id: "req-a9",
    type: "Short Leave",
    subtype: "Personal Work",
    employeeCode: "51",
    employeeName: "Kunal Kikani",
    designation: "video editing",
    department: "video editing",
    details: {
      date: "09-07-2026",
      inTime: "02:00 PM",
      outTime: "04:00 PM",
      totalHours: "2 hrs",
      reason: "Bank work",
    },
    submittedDate: "09-07-2026 11:00 AM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "09-07-2026 11:30 AM",
    remarks: "Short leave approved.",
  },
  {
    id: "req-a10",
    type: "Leave",
    subtype: "Casual Leave",
    employeeCode: "55",
    employeeName: "Mansi Boghra",
    designation: "Python",
    department: "Developer",
    details: {
      fromDate: "Mon 06 Jul",
      toDate: "Tue 07 Jul",
      totalDays: "2 Days",
      reason: "Family function",
    },
    submittedDate: "03-07-2026 05:00 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "04-07-2026 10:00 AM",
    remarks: "Have a nice break.",
  },
  {
    id: "req-a11",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "50",
    employeeName: "Vivek Rathod",
    designation: "Graphic Designer",
    department: "Graphic Designer",
    details: {
      date: "05-07-2026",
      inTime: "09:30 AM",
      outTime: "06:30 PM",
      reason: "Forgot to punch out",
    },
    submittedDate: "06-07-2026 09:00 AM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "06-07-2026 11:00 AM",
    remarks: "Punches verified.",
  },
  {
    id: "req-a12",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "49",
    employeeName: "Rahi Patel",
    designation: "video editing",
    department: "video editing",
    details: {
      date: "03-07-2026",
      inTime: "09:15 AM",
      outTime: "06:15 PM",
      reason: "Biometric reader issue",
    },
    submittedDate: "03-07-2026 06:20 PM",
    status: "approved",
    approvedBy: "Balkrushn koladiya",
    actionDate: "04-07-2026 09:30 AM",
    remarks: "Approved.",
  },

  // --- REJECTED REQUESTS ---
  {
    id: "req-r1",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "54",
    employeeName: "Divyesh Pipaliya",
    designation: "marketing",
    department: "Marketing",
    details: {
      date: "01-07-2026",
      inTime: "09:00 AM",
      outTime: "06:00 PM",
      reason: "Punch missed",
    },
    submittedDate: "02-07-2026 10:00 AM",
    status: "rejected",
    rejectedBy: "Balkrushn koladiya",
    actionDate: "02-07-2026 02:00 PM",
    remarks: "Insufficient proof provided for presence on date.",
  },
  {
    id: "req-r2",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "34",
    employeeName: "Kamlesh Sahu",
    designation: "React.js",
    department: "Developer",
    details: {
      date: "08-07-2026",
      inTime: "10:30 AM",
      outTime: "06:30 PM",
      reason: "Late arrival punch regularize",
    },
    submittedDate: "09-07-2026 09:15 AM",
    status: "rejected",
    rejectedBy: "Balkrushn koladiya",
    actionDate: "09-07-2026 11:45 AM",
    remarks: "Late arrival beyond allowed monthly quota.",
  },
  {
    id: "req-r3",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "45",
    employeeName: "Nishant Talaviya",
    designation: "System Architecture",
    department: "Intern",
    details: {
      date: "08-07-2026",
      inTime: "09:00 AM",
      outTime: "06:00 PM",
      reason: "Forgot punch",
    },
    submittedDate: "09-07-2026 10:00 AM",
    status: "rejected",
    rejectedBy: "Balkrushn koladiya",
    actionDate: "09-07-2026 01:30 PM",
    remarks: "No manager approval pre-obtained.",
  },
  {
    id: "req-r4",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "34",
    employeeName: "Kamlesh Sahu",
    designation: "React.js",
    department: "Developer",
    details: {
      date: "07-07-2026",
      inTime: "09:30 AM",
      outTime: "06:30 PM",
      reason: "Work from home punch",
    },
    submittedDate: "08-07-2026 09:30 AM",
    status: "rejected",
    rejectedBy: "Balkrushn koladiya",
    actionDate: "08-07-2026 04:00 PM",
    remarks: "WFH not approved prior to date.",
  },
  {
    id: "req-r5",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "45",
    employeeName: "Nishant Talaviya",
    designation: "System Architecture",
    department: "Intern",
    details: {
      date: "07-07-2026",
      inTime: "09:00 AM",
      outTime: "06:00 PM",
      reason: "Punch reader failure",
    },
    submittedDate: "08-07-2026 10:30 AM",
    status: "rejected",
    rejectedBy: "Balkrushn koladiya",
    actionDate: "08-07-2026 04:15 PM",
    remarks: "System logs show normal reader operation on 07-07-2026.",
  },
  {
    id: "req-r6",
    type: "Attendance",
    subtype: "New Punch Added",
    employeeCode: "47",
    employeeName: "Pruthvi Goti",
    designation: "Flutter",
    department: "Developer",
    details: {
      date: "06-07-2026",
      inTime: "09:00 AM",
      outTime: "06:00 PM",
      reason: "Device failure",
    },
    submittedDate: "07-07-2026 09:00 AM",
    status: "rejected",
    rejectedBy: "Balkrushn koladiya",
    actionDate: "07-07-2026 11:30 AM",
    remarks: "Rejected due to lack of confirmation.",
  },
];
